package com.siave.persistence.model;

import java.util.ArrayList;
import java.util.List;

public class CatsupercategoriaExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table catsupercategoria
     *
     * @mbggenerated Wed Feb 10 16:34:47 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table catsupercategoria
     *
     * @mbggenerated Wed Feb 10 16:34:47 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table catsupercategoria
     *
     * @mbggenerated Wed Feb 10 16:34:47 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catsupercategoria
     *
     * @mbggenerated Wed Feb 10 16:34:47 CST 2016
     */
    public CatsupercategoriaExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catsupercategoria
     *
     * @mbggenerated Wed Feb 10 16:34:47 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catsupercategoria
     *
     * @mbggenerated Wed Feb 10 16:34:47 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catsupercategoria
     *
     * @mbggenerated Wed Feb 10 16:34:47 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catsupercategoria
     *
     * @mbggenerated Wed Feb 10 16:34:47 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catsupercategoria
     *
     * @mbggenerated Wed Feb 10 16:34:47 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catsupercategoria
     *
     * @mbggenerated Wed Feb 10 16:34:47 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catsupercategoria
     *
     * @mbggenerated Wed Feb 10 16:34:47 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catsupercategoria
     *
     * @mbggenerated Wed Feb 10 16:34:47 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catsupercategoria
     *
     * @mbggenerated Wed Feb 10 16:34:47 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catsupercategoria
     *
     * @mbggenerated Wed Feb 10 16:34:47 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table catsupercategoria
     *
     * @mbggenerated Wed Feb 10 16:34:47 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdCatSuperCategoriaIsNull() {
            addCriterion("idCatSuperCategoria is null");
            return (Criteria) this;
        }

        public Criteria andIdCatSuperCategoriaIsNotNull() {
            addCriterion("idCatSuperCategoria is not null");
            return (Criteria) this;
        }

        public Criteria andIdCatSuperCategoriaEqualTo(Byte value) {
            addCriterion("idCatSuperCategoria =", value, "idCatSuperCategoria");
            return (Criteria) this;
        }

        public Criteria andIdCatSuperCategoriaNotEqualTo(Byte value) {
            addCriterion("idCatSuperCategoria <>", value, "idCatSuperCategoria");
            return (Criteria) this;
        }

        public Criteria andIdCatSuperCategoriaGreaterThan(Byte value) {
            addCriterion("idCatSuperCategoria >", value, "idCatSuperCategoria");
            return (Criteria) this;
        }

        public Criteria andIdCatSuperCategoriaGreaterThanOrEqualTo(Byte value) {
            addCriterion("idCatSuperCategoria >=", value, "idCatSuperCategoria");
            return (Criteria) this;
        }

        public Criteria andIdCatSuperCategoriaLessThan(Byte value) {
            addCriterion("idCatSuperCategoria <", value, "idCatSuperCategoria");
            return (Criteria) this;
        }

        public Criteria andIdCatSuperCategoriaLessThanOrEqualTo(Byte value) {
            addCriterion("idCatSuperCategoria <=", value, "idCatSuperCategoria");
            return (Criteria) this;
        }

        public Criteria andIdCatSuperCategoriaIn(List<Byte> values) {
            addCriterion("idCatSuperCategoria in", values, "idCatSuperCategoria");
            return (Criteria) this;
        }

        public Criteria andIdCatSuperCategoriaNotIn(List<Byte> values) {
            addCriterion("idCatSuperCategoria not in", values, "idCatSuperCategoria");
            return (Criteria) this;
        }

        public Criteria andIdCatSuperCategoriaBetween(Byte value1, Byte value2) {
            addCriterion("idCatSuperCategoria between", value1, value2, "idCatSuperCategoria");
            return (Criteria) this;
        }

        public Criteria andIdCatSuperCategoriaNotBetween(Byte value1, Byte value2) {
            addCriterion("idCatSuperCategoria not between", value1, value2, "idCatSuperCategoria");
            return (Criteria) this;
        }

        public Criteria andNombreSuperCategoriaIsNull() {
            addCriterion("nombreSuperCategoria is null");
            return (Criteria) this;
        }

        public Criteria andNombreSuperCategoriaIsNotNull() {
            addCriterion("nombreSuperCategoria is not null");
            return (Criteria) this;
        }

        public Criteria andNombreSuperCategoriaEqualTo(String value) {
            addCriterion("nombreSuperCategoria =", value, "nombreSuperCategoria");
            return (Criteria) this;
        }

        public Criteria andNombreSuperCategoriaNotEqualTo(String value) {
            addCriterion("nombreSuperCategoria <>", value, "nombreSuperCategoria");
            return (Criteria) this;
        }

        public Criteria andNombreSuperCategoriaGreaterThan(String value) {
            addCriterion("nombreSuperCategoria >", value, "nombreSuperCategoria");
            return (Criteria) this;
        }

        public Criteria andNombreSuperCategoriaGreaterThanOrEqualTo(String value) {
            addCriterion("nombreSuperCategoria >=", value, "nombreSuperCategoria");
            return (Criteria) this;
        }

        public Criteria andNombreSuperCategoriaLessThan(String value) {
            addCriterion("nombreSuperCategoria <", value, "nombreSuperCategoria");
            return (Criteria) this;
        }

        public Criteria andNombreSuperCategoriaLessThanOrEqualTo(String value) {
            addCriterion("nombreSuperCategoria <=", value, "nombreSuperCategoria");
            return (Criteria) this;
        }

        public Criteria andNombreSuperCategoriaLike(String value) {
            addCriterion("nombreSuperCategoria like", value, "nombreSuperCategoria");
            return (Criteria) this;
        }

        public Criteria andNombreSuperCategoriaNotLike(String value) {
            addCriterion("nombreSuperCategoria not like", value, "nombreSuperCategoria");
            return (Criteria) this;
        }

        public Criteria andNombreSuperCategoriaIn(List<String> values) {
            addCriterion("nombreSuperCategoria in", values, "nombreSuperCategoria");
            return (Criteria) this;
        }

        public Criteria andNombreSuperCategoriaNotIn(List<String> values) {
            addCriterion("nombreSuperCategoria not in", values, "nombreSuperCategoria");
            return (Criteria) this;
        }

        public Criteria andNombreSuperCategoriaBetween(String value1, String value2) {
            addCriterion("nombreSuperCategoria between", value1, value2, "nombreSuperCategoria");
            return (Criteria) this;
        }

        public Criteria andNombreSuperCategoriaNotBetween(String value1, String value2) {
            addCriterion("nombreSuperCategoria not between", value1, value2, "nombreSuperCategoria");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table catsupercategoria
     *
     * @mbggenerated do_not_delete_during_merge Wed Feb 10 16:34:47 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table catsupercategoria
     *
     * @mbggenerated Wed Feb 10 16:34:47 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}