package com.siave.persistence.model;

public class Catsupercategoria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column catsupercategoria.idCatSuperCategoria
     *
     * @mbggenerated Wed Feb 10 16:34:47 CST 2016
     */
    private Byte idCatSuperCategoria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column catsupercategoria.nombreSuperCategoria
     *
     * @mbggenerated Wed Feb 10 16:34:47 CST 2016
     */
    private String nombreSuperCategoria;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column catsupercategoria.idCatSuperCategoria
     *
     * @return the value of catsupercategoria.idCatSuperCategoria
     *
     * @mbggenerated Wed Feb 10 16:34:47 CST 2016
     */
    public Byte getIdCatSuperCategoria() {
        return idCatSuperCategoria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column catsupercategoria.idCatSuperCategoria
     *
     * @param idCatSuperCategoria the value for catsupercategoria.idCatSuperCategoria
     *
     * @mbggenerated Wed Feb 10 16:34:47 CST 2016
     */
    public void setIdCatSuperCategoria(Byte idCatSuperCategoria) {
        this.idCatSuperCategoria = idCatSuperCategoria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column catsupercategoria.nombreSuperCategoria
     *
     * @return the value of catsupercategoria.nombreSuperCategoria
     *
     * @mbggenerated Wed Feb 10 16:34:47 CST 2016
     */
    public String getNombreSuperCategoria() {
        return nombreSuperCategoria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column catsupercategoria.nombreSuperCategoria
     *
     * @param nombreSuperCategoria the value for catsupercategoria.nombreSuperCategoria
     *
     * @mbggenerated Wed Feb 10 16:34:47 CST 2016
     */
    public void setNombreSuperCategoria(String nombreSuperCategoria) {
        this.nombreSuperCategoria = nombreSuperCategoria == null ? null : nombreSuperCategoria.trim();
    }
}