package com.siave.persistence.dao;

import com.siave.persistence.model.Catsupercategoria;
import com.siave.persistence.model.CatsupercategoriaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CatsupercategoriaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catsupercategoria
     *
     * @mbggenerated Wed Feb 10 16:34:47 CST 2016
     */
    int countByExample(CatsupercategoriaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catsupercategoria
     *
     * @mbggenerated Wed Feb 10 16:34:47 CST 2016
     */
    int deleteByExample(CatsupercategoriaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catsupercategoria
     *
     * @mbggenerated Wed Feb 10 16:34:47 CST 2016
     */
    int deleteByPrimaryKey(Byte idCatSuperCategoria);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catsupercategoria
     *
     * @mbggenerated Wed Feb 10 16:34:47 CST 2016
     */
    int insert(Catsupercategoria record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catsupercategoria
     *
     * @mbggenerated Wed Feb 10 16:34:47 CST 2016
     */
    int insertSelective(Catsupercategoria record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catsupercategoria
     *
     * @mbggenerated Wed Feb 10 16:34:47 CST 2016
     */
    List<Catsupercategoria> selectByExample(CatsupercategoriaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catsupercategoria
     *
     * @mbggenerated Wed Feb 10 16:34:47 CST 2016
     */
    Catsupercategoria selectByPrimaryKey(Byte idCatSuperCategoria);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catsupercategoria
     *
     * @mbggenerated Wed Feb 10 16:34:47 CST 2016
     */
    int updateByExampleSelective(@Param("record") Catsupercategoria record, @Param("example") CatsupercategoriaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catsupercategoria
     *
     * @mbggenerated Wed Feb 10 16:34:47 CST 2016
     */
    int updateByExample(@Param("record") Catsupercategoria record, @Param("example") CatsupercategoriaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catsupercategoria
     *
     * @mbggenerated Wed Feb 10 16:34:47 CST 2016
     */
    int updateByPrimaryKeySelective(Catsupercategoria record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catsupercategoria
     *
     * @mbggenerated Wed Feb 10 16:34:47 CST 2016
     */
    int updateByPrimaryKey(Catsupercategoria record);
}